# Generated by Django 3.0.6 on 2020-05-28 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200527_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'admin_data',
            },
        ),
        migrations.AlterField(
            model_name='student_data',
            name='b_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='register.Branch'),
        ),
    ]
