# Generated by Django 3.0.6 on 2020-05-29 10:43

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20200528_1912'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student_data',
            managers=[
                ('roll_man', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='student_data',
            name='attendance',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
