# Generated by Django 3.0.6 on 2020-05-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20200529_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='attendance',
            field=models.IntegerField(default=0),
        ),
    ]
