# Generated by Django 3.0.6 on 2020-06-05 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20200530_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='branch',
            field=models.ForeignKey(default='UD', on_delete=django.db.models.deletion.CASCADE, to='register.Branch'),
        ),
    ]
